name: weather-crawler
on:
  workflow_dispatch:
jobs:
  build:
    name: scraping
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: sleep 5
      - run: docker-compose exec -T develop python3 main.py
      - run: docker-compose down
